import {test} from 'node:test';import assert from 'node:assert/strict';
import * as impl from '../src/engine.js';
test('cold synthesis never blocks dialing; answer polls outside Gather then plays one whole clip',async()=>{
 const x=setup();let ready=false;const prompts=[];x.deps.speech=async kind=>{prompts.push(kind);return ready?{status:'ready',url:'https://app/one-whole-utterance'}:{status:'pending'};};
 x.e=new impl.Engine(x.deps);await x.e.start(inbound);await x.e.wait();await x.e.status({CallSid:child,CallStatus:'ringing'});
 assert.equal(x.events.filter(v=>v[0]==='dial').length,1);assert.doesNotMatch(await x.e.wait(),/<Play/);
 const pending=await x.e.answer({CallSid:child});assert.doesNotMatch(pending,/<Gather/);assert.match(pending,/<Redirect/);
 ready=true;const answer=await x.e.answer({CallSid:child});assert.equal((answer.match(/<Play>/g)||[]).length,1);assert.match(answer,/timeout="10"/);assert.match(answer,/one-whole-utterance/);
});
test('speech failure fails closed without joining; pending has bounded deadline',async()=>{
 const x=await ringing();x.deps.speech=async()=>({status:'pending'});await x.e.answer({CallSid:child});x.advance(22000);
 assert.match(await x.e.answer({CallSid:child}),/<Hangup/);assert.equal(x.db.get('call').phase,'failed');
 const y=await ringing();y.deps.speech=async()=>({status:'failed'});assert.match(await y.e.answer({CallSid:child}),/<Hangup/);assert.equal(y.db.get('call').phase,'failed');
});
function setup(){const db=new Map();const events=[];let clock=1000;const deps={email:{EMAIL_FROM:'sms@example.com',EMAIL_TO:'inbox@example.com'},now:()=>clock,save:(k,v)=>db.set(k,structuredClone(v)),load:k=>structuredClone(db.get(k)),alarm:async t=>events.push(['alarm',t]),mail:async p=>{events.push(['mail',p]);return {messageId:'test-email'};},inspectCall:async()=>({direction:'inbound',status:'in-progress',from:'+12025550102',to:'+12025550100'}),dial:async p=>{events.push(['dial',p]);return {sid:'CA'+'2'.repeat(32)};},update:async(sid,p)=>events.push(['update',sid,p]),prewarm:async()=>{},speech:async(kind)=>({status:'ready',url:'https://app/whole-'+kind}),audio:async parts=>'https://app/audio?parts='+parts.join(','),origin:'https://app',allowed:['+12025550100'],from:'+12025550100',destination:'+442079460123'};return {db,events,deps,advance:n=>clock+=n};}
const parent='CA'+'1'.repeat(32),child='CA'+'2'.repeat(32);const inbound={CallSid:parent,From:'+12025550102',To:'+12025550100'};
test('initial real inbound ringing call can enter waiting conference',async()=>{const x=setup();const original=x.deps.inspectCall;x.deps.inspectCall=async()=>({...await original(),status:'ringing'});const e=new impl.Engine(x.deps);assert.match(await e.start(inbound),/<Conference/);assert.equal(x.db.get('call').phase,'waiting');});
async function ringing(){const x=setup();x.e=new impl.Engine(x.deps);await x.e.start(inbound);await x.e.wait();await x.e.status({CallSid:child,CallStatus:'ringing'});return x;}
test('only child press 1 after private prompt enters conference',async()=>{const x=await ringing();assert.match(await x.e.answer({CallSid:child}),/timeout="10"/);await assert.rejects(x.e.accept({CallSid:parent,Digits:'1'}));const r=await x.e.accept({CallSid:child,Digits:'1'});assert.match(r,/startConferenceOnEnter="true"/);assert.equal(x.db.get('call').phase,'accepted');});
for(const outcome of ['busy','no-answer','failed','canceled','completed'])test(`terminal ${outcome} before acceptance tells caller unavailable and disconnects`,async()=>{const x=await ringing();await x.e.status({CallSid:child,CallStatus:outcome});assert.equal(x.db.get('call').phase,'failed');assert.ok(x.events.some(v=>v[0]==='update'&&v[1]===parent&&v[2].Twiml.includes('unavailable')&&v[2].Twiml.includes('<Hangup/>')));});
for(const digit of ['', '2'])test(`reject/no input (${digit}) cannot bridge`,async()=>{const x=await ringing();await x.e.answer({CallSid:child});assert.doesNotMatch(await x.e.accept({CallSid:child,Digits:digit}),/<Conference/);assert.equal(x.db.get('call').phase,'failed');});
test('25-second ring watchdog cancels outbound, but never cancels prompt/accepted call',async()=>{const x=await ringing();x.advance(25000);await x.e.alarm();assert.equal(x.db.get('call').phase,'failed');assert.ok(x.events.some(v=>v[0]==='update'&&v[1]===child&&v[2].Status==='completed'));const y=await ringing();await y.e.answer({CallSid:child});y.advance(25000);await y.e.alarm();assert.equal(y.db.get('call').phase,'screening');});
test('caller hangup cancels outgoing leg and retries cannot start another',async()=>{const x=await ringing();await x.e.event({CallSid:parent,StatusCallbackEvent:'participant-leave'});await x.e.wait();assert.equal(x.db.get('call').phase,'ended');assert.equal(x.events.filter(v=>v[0]==='dial').length,1);});
test('answer and delayed callback after acceptance cannot regress or interrupt call',async()=>{const x=await ringing();await x.e.answer({CallSid:child});await x.e.accept({CallSid:child,Digits:'1'});await x.e.status({CallSid:child,CallStatus:'ringing'});assert.equal(x.db.get('call').phase,'accepted');await x.e.status({CallSid:child,CallStatus:'completed'});assert.equal(x.events.filter(v=>v[0]==='update'&&v[1]===parent).length,0);});
test('SMS persistent reservation deduplicates concurrent retries without changing content',async()=>{const x=setup();const e=new impl.Engine(x.deps);const p={From:'+1',To:'+2',Body:'original\n日本語'};await Promise.all([e.sms(p),e.sms(p)]);assert.equal(x.events.filter(v=>v[0]==='mail').length,1);assert.equal(x.db.get('sms').status,'sent');});
test('outbound starts only while caller waiting; announcement waits for ringing',async()=>{const x=setup(),e=new impl.Engine(x.deps);const r=await e.start(inbound);assert.match(r,/startConferenceOnEnter="false"/);assert.equal(x.events.filter(v=>v[0]==='dial').length,0);assert.doesNotMatch(await e.wait(),/parts=connecting/);assert.equal(x.events.filter(v=>v[0]==='dial').length,1);await e.status({CallSid:child,CallStatus:'ringing'});assert.match(await e.wait(),/whole-connecting/);assert.equal(x.events.find(v=>v[0]==='dial')[1].To,'+442079460123');assert.equal(x.events.find(v=>v[0]==='dial')[1].Timeout,25);assert.equal(x.events.find(v=>v[0]==='dial')[1].Record,false);});
