const {test}=require('node:test');const a=require('node:assert/strict');const {run}=require('../src/app.cjs');
const parent='CA'+'1'.repeat(32),child='CA'+'2'.repeat(32),account='AC'+'a'.repeat(32);const c={ACCOUNT_SID:account,DOMAIN_NAME:'example.twil.io',ALLOWED_NUMBERS:'+442079460124',DESTINATION:'+442079460125',OUTBOUND_NUMBER:'+442079460124',LIVE_CALLS_ENABLED:'true',UNAVAILABLE_PATH:'/unavailable.mp3'};
function deps(){const docs=new Map();const effects=[];return {docs,effects,get:async k=>docs.get(k),set:async(k,v)=>docs.set(k,v),create:async(k,v)=>{if(docs.has(k))return false;docs.set(k,v);return true},call:async()=>({sid:parent,direction:'inbound',status:'in-progress',from:'+442079460123',to:'+442079460124'}),speech:async()=>({status:'ready',url:'https://media.twilio.com/audio'}),dial:async x=>{effects.push(x);return {sid:child}},update:async(id,x)=>effects.push({id,...x})};}
const event=mode=>({mode,AccountSid:account,CallSid:parent,From:'+442079460123',To:'+442079460124',parent});
test('parallel announcement and native call; only1 bridges;25sec ring and10sec gather',async()=>{const d=deps();const v=await run(c,event('voice'),d);a.match(v,/startConferenceOnEnter="false"/);const wait=await run(c,event('wait'),d);a.match(wait,/<Play>/);a.equal(d.effects[0].Timeout,25);a.equal(d.effects[0].Record,false);await run(c,event('wait'),d);a.equal(d.effects.length,1);const ans=await run(c,{...event('answer'),CallSid:child},d);a.match(ans,/timeout="10"/);a.match(ans,/<Gather[^>]*><Play>/);const yes=await run(c,{...event('accept'),CallSid:child,Digits:'1'},d);a.match(yes,/startConferenceOnEnter="true"/);});
test('wrong child rejected and decline never bridges',async()=>{const d=deps();await run(c,event('voice'),d);await run(c,event('wait'),d);await a.rejects(run(c,{...event('answer'),CallSid:'CA'+'3'.repeat(32)},d),/Wrong child/);await run(c,{...event('answer'),CallSid:child},d);const no=await run(c,{...event('accept'),CallSid:child,Digits:'2'},d);a.doesNotMatch(no,/<Conference/);a.ok(d.effects.some(x=>x.id===parent&&x.Twiml.includes('unavailable.mp3')));});
test('isolated deploy refuses any real voice action',async()=>{await a.rejects(run({...c,LIVE_CALLS_ENABLED:'false'},event('voice'),deps()),/disabled/)});
test('empty gather result plays unavailable and hangs up both legs',async()=>{const d=deps();await run(c,event('voice'),d);await run(c,event('wait'),d);await run(c,{...event('answer'),CallSid:child},d);const result=await run(c,{...event('accept'),CallSid:child,Digits:''},d);a.match(result,/<Hangup/);a.ok(d.effects.some(x=>x.id===parent&&x.Twiml.includes('<Hangup')));a.ok(d.effects.some(x=>x.id===child&&x.Status==='completed'));});
test('no answer terminal callback sends unavailable without bridging',async()=>{const d=deps();await run(c,event('voice'),d);await run(c,event('wait'),d);await run(c,{...event('status'),CallSid:child,CallStatus:'no-answer'},d);a.equal(d.docs.get('call-'+parent+'-decision').value,'failed');a.ok(d.effects.some(x=>x.id===parent&&x.Twiml.includes('unavailable.mp3')));});
test('accepted decision is not overwritten by duplicate terminal callback',async()=>{const d=deps();await run(c,event('voice'),d);await run(c,event('wait'),d);await run(c,{...event('answer'),CallSid:child},d);await run(c,{...event('accept'),CallSid:child,Digits:'1'},d);const before=d.effects.length;await run(c,{...event('status'),CallSid:child,CallStatus:'completed'},d);a.equal(d.effects.length,before);a.equal(d.docs.get('call-'+parent+'-decision').value,'accepted');});
